# Generated by Django 3.2.18 on 2023-03-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DAILY', 'Top 50 daily'), ('WEEKLY', 'Top 50 weekly'), ('VIRAL', 'Top 50 viral')], max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=50)),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('duration', models.IntegerField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('key', models.IntegerField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.BooleanField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('time_signature', models.IntegerField()),
                ('valence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SongInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='api.playlist')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='api.song')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='api.SongInPlaylist', to='api.Song'),
        ),
    ]
