# Generated by Django 3.2.18 on 2023-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Minor'), (1, 'Major')]),
        ),
    ]
