# Generated by Django 3.2.18 on 2023-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_song_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='uri',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
