# Generated by Django 3.2.18 on 2023-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playlist_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
