# Generated by Django 3.2.18 on 2023-03-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_playlist_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='duration_ms',
        ),
    ]
