# Generated by Django 3.2.18 on 2023-03-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country'),
        ),
    ]
